In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [2]:
pwd

'C:\\Users\\lenovo-pc'

In [3]:
os.chdir('D:\\Data Science')

In [4]:
#Load the data
dataset = pd.read_csv('norway_new_car_sales_by_make.csv')

In [5]:
dataset.head()

   Year  Month        Make  Quantity   Pct
0  2007      1      Toyota      2884  22.7
1  2007      1  Volkswagen      2521  19.9
2  2007      1     Peugeot      1029   8.1
3  2007      1        Ford       870   6.9
4  2007      1       Volvo       693   5.5

In [6]:
# Create a column “Period” with both the Year and the Month
dataset['Period'] = dataset['Year'].astype(str) + '-' + dataset['Month'].astype(str)

In [7]:
# Weuse the datetime formatting to make sure format is consistent
dataset['Period'] = pd.to_datetime(dataset['Period']).dt.strftime("%Y-%m")

In [9]:
#Create a pivot of the data to show the periods on columns and the car makers on rows 
df = pd.pivot_table(data = dataset, index = 'Make', columns = 'Period', values = 'Quantity', aggfunc = 'sum', fill_value = 0)

In [10]:
df.head()

Period,2007-01,2007-02,2007-03,2007-04,2007-05,2007-06,2007-07,2007-08,2007-09,2007-10,...,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01
Make,,,,,,,,,,,,,,,,,,,,,
Alfa Romeo,16,9,21,20,17,21,14,12,15,10,...,3,1,2,1,6,15,3,4,3,6
Aston Martin,0,0,1,0,4,3,3,0,0,0,...,0,0,1,0,0,0,0,0,0,0
Audi,599,498,682,556,630,498,562,590,393,554,...,685,540,551,687,794,688,603,645,827,565
BMW,352,335,365,360,431,477,403,348,271,562,...,1052,832,808,636,1031,1193,1096,1663,866,1540
Bentley,0,0,0,0,0,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,0

In [12]:
df.loc['Toyota'][0]

2884

In [17]:
# Print data to Excel for reference 
df.to_csv('Clean Demand.csv')

In [18]:
# def import_data():
#  data = pd.read_csv(“norway_new_car_sales_by_make.csv”)
#  data[“Period”] = data[“Year”].astype(str) + “-” + data[“Month”].astype(str)
#  data[“Period”] = pd.to_datetime(data[“Period”]).dt.strftime(“%Y-%m”)
#  df = pd.pivot_table(data=data,values=”Quantity”,index=”Make”,columns=”Period”,aggfunc=’sum’,fill_value=0)
#  return df

In [31]:
def datasets(df, x_len=12, y_len=1, y_test_len=12):
    D = df.values
    periods = D.shape[1] #periods =121
# Training set creation: run through all the possible time windows
    loops = periods + 1 - x_len - y_len - y_test_len 
    train = []
    for col in range(loops):
        train.append(D[:,col:col+x_len+y_len])
        train = np.vstack(train)
        print(train)
        X_train, Y_train = np.split(train,[x_len],axis=1)
        print(X_train)
        print(Y_train)
         # this data formatting is needed if we only predict a single period
        if y_len == 1:
            Y_train = Y_train.ravel()
            Y_test = Y_test.ravel()
 
    return X_train, Y_train, X_test, Y_test

In [41]:

D = df.values
periods = D.shape[1] #periods =121
# Training set creation: run through all the possible time windows
x_len, y_len, y_test_len = 12,1,12
loops = 121 + 1 - 12 - 1 - 12 
train = []
for col in range(loops):
    train.append(D[:,col:col+x_len+y_len])
    print(train)
    train = np.vstack(train)
    print('Train', train)
    X_train, Y_train = np.split(train,[x_len],axis=1)
    print('X_train', X_train)
    print('Y_train', Y_train)
# Test set creation: unseen “future” data with the demand just before
max_col_test = periods - x_len - y_len + 1
test = []
for col in range(loops,max_col_test):
    test.append(D[:,col:col+x_len+y_len])
    test = np.vstack(test)
    X_test, Y_test = np.split(test,[x_len],axis=1)
 # this data formatting is needed if we only predict a single period
if y_len == 1:
    Y_train = Y_train.ravel()
    Y_test = Y_test.ravel()
    print(Y_train)
    print(Y_test)

[array([[  16,    9,   21,   20,   17,   21,   14,   12,   15,   10,   18,
          21,   15],
       [   0,    0,    1,    0,    4,    3,    3,    0,    0,    0,    0,
           0,    0],
       [ 599,  498,  682,  556,  630,  498,  562,  590,  393,  554,  448,
         462,  429],
       [ 352,  335,  365,  360,  431,  477,  403,  348,  271,  562,  525,
         512,  368],
       [   0,    0,    0,    0,    0,    1,    0,    0,    0,    0,    0,
           1,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,    1,    4,    2,    0,    1,    0,    3,    0,    1,    0,
           1,    0],
       [  20,   35,   52,   79,   65,   74,   78,   67,   57,   47,   50,
          44,   28],
       [   0,    3,    0,    0,    0,    1,    0,    0,    0,    1,    0,
           0,    0],
       [   4,    5,    3,   11,    8,    5,    5,    1,    4,    4,    9,
           4,    5],
       [ 263,  247,  239,  179,  223,  277,  281,  288,  184,  202,  206,
         120,  146],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [  15,   22,   27,   17,   36,   37,   33,   40,   26,   27,   19,
          16,   24],
       [  33,   24,   25,   25,   29,   23,   26,   13,   12,   21,   25,
          16,   16],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   9,    6,   20,    7,   18,   10,   12,   23,   32,   28,   40,
           9,   22],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [ 870,  686,  766,  451,  648,  772, 1006,  816,  679,  693,  566,
         821,  942],
       [ 423,  356,  399,  351,  520,  624,  401,  296,  358,  428,  509,
         471,  549],
       [  97,  149,  228,  142,  155,  204,  182,  196,  247,  220,  156,
         128,   97],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    1,    0,
           0,    0],
       [   4,    0,    5,    5,    0,    0,    0,    1,    0,    0,    0,
           0,    0],
       [   3,    5,    9,    5,    5,    8,   12,    5,    5,    7,    7,
           2,    2],
       [   2,    6,   33,   10,   72,   68,   56,   51,   34,   52,   46,
          43,   32],
       [  55,  119,  171,   92,  169,  159,  137,  122,  158,  145,  161,
         132,  111],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    1,    1,    0,    0,
           0,    0],
       [  14,   30,   40,   42,   91,   47,   32,   28,   32,   39,   23,
          56,   21],
       [  22,   17,   18,   18,   10,   17,   16,   30,   25,   23,   22,
          10,   30],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [  26,   32,   28,   31,   30,   37,   28,   24,   26,   26,   48,
          28,   55],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    1,    1,    1,
           1,    0],
       [ 191,  239,  319,  249,  325,  296,  294,  237,  266,  247,  287,
         194,  280],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [ 362,  410,  387,  387,  422,  421,  469,  435,  298,  376,  447,
         456,  374],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [ 136,  262,  512,  104,  222,  414,  381,  681,  553,  324,  299,
         351,  337],
       [   0,    0,    0,    4,    2,    0,    0,    0,    1,    0,    0,
           0,    0],
       [   2,    6,    1,    0,    0,    0,    1,    0,    1,    1,    0,
           1,    3],
       [ 127,  134,  327,  328,  382,  364,  277,  348,  432,  518,  530,
         244,  472],
       [ 622,  551,  578,  534,  771,  683,  685,  472,  414,  547,  477,
         481,  334],
       [1029,  621,  867,  547,  743,  569,  749,  531,  426,  707,  479,
         225,  592],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,    2,   14,    7,    4,    5,    3,    1,    4,    3,    3,
           2,    0],
       [ 168,   84,  131,   92,  109,  107,  124,  100,   69,   75,   74,
          57,   59],
       [ 169,  175,  243,  191,  241,  195,  204,  103,  220,  234,  233,
         307,  114],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [ 665,  463,  491,  438,  517,  512,  489,  476,  354,  438,  447,
         578,  360],
       [   1,    5,    0,    1,    2,    8,    8,   13,    3,    6,    2,
           6,    4],
       [   1,    2,    0,    0,    3,    5,    1,    3,    2,    1,    3,
           3,    0],
       [  26,   18,    7,   77,   78,   65,   51,   92,   85,  141,  220,
         224,  161],
       [ 258,  264,  333,  347,  420,  262,  296,  392,  314,  333,  310,
         201,  344],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   2,    0,    0,    1,    0,    0,    0,    1,    0,    0,    0,
           0,    0],
       [2884, 1885, 1833, 1300, 1866, 1620, 1901, 1783, 1303, 1648, 1579,
        1081, 1758],
       [2521, 1517, 1428, 1257, 1934, 1531, 1777, 1665, 1373, 1941, 1473,
        1272, 1224],
       [ 693,  570,  656,  587,  805,  662, 1064,  498,  662, 1014,  710,
         641,  593],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0]], dtype=int64)]
Train [[  16    9   21   20   17   21   14   12   15   10   18   21   15]
 [   0    0    1    0    4    3    3    0    0    0    0    0    0]
 [ 599  498  682  556  630  498  562  590  393  554  448  462  429]
 [ 352  335  365  360  431  477  403  348  271  562  525  512  368]
 [   0    0    0    0    0    1    0    0    0    0    0    1    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    1    4    2    0    1    0    3    0    1    0    1    0]
 [  20   35   52   79   65   74   78   67   57   47   50   44   28]
 [   0    3    0    0    0    1    0    0    0    1    0    0    0]
 [   4    5    3   11    8    5    5    1    4    4    9    4    5]
 [ 263  247  239  179  223  277  281  288  184  202  206  120  146]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [  15   22   27   17   36   37   33   40   26   27   19   16   24]
 [  33   24   25   25   29   23   26   13   12   21   25   16   16]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   9    6   20    7   18   10   12   23   32   28   40    9   22]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [ 870  686  766  451  648  772 1006  816  679  693  566  821  942]
 [ 423  356  399  351  520  624  401  296  358  428  509  471  549]
 [  97  149  228  142  155  204  182  196  247  220  156  128   97]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    1    0    0    0]
 [   4    0    5    5    0    0    0    1    0    0    0    0    0]
 [   3    5    9    5    5    8   12    5    5    7    7    2    2]
 [   2    6   33   10   72   68   56   51   34   52   46   43   32]
 [  55  119  171   92  169  159  137  122  158  145  161  132  111]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    1    1    0    0    0    0]
 [  14   30   40   42   91   47   32   28   32   39   23   56   21]
 [  22   17   18   18   10   17   16   30   25   23   22   10   30]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [  26   32   28   31   30   37   28   24   26   26   48   28   55]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    1    1    1    1    0]
 [ 191  239  319  249  325  296  294  237  266  247  287  194  280]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [ 362  410  387  387  422  421  469  435  298  376  447  456  374]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [ 136  262  512  104  222  414  381  681  553  324  299  351  337]
 [   0    0    0    4    2    0    0    0    1    0    0    0    0]
 [   2    6    1    0    0    0    1    0    1    1    0    1    3]
 [ 127  134  327  328  382  364  277  348  432  518  530  244  472]
 [ 622  551  578  534  771  683  685  472  414  547  477  481  334]
 [1029  621  867  547  743  569  749  531  426  707  479  225  592]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    2   14    7    4    5    3    1    4    3    3    2    0]
 [ 168   84  131   92  109  107  124  100   69   75   74   57   59]
 [ 169  175  243  191  241  195  204  103  220  234  233  307  114]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [ 665  463  491  438  517  512  489  476  354  438  447  578  360]
 [   1    5    0    1    2    8    8   13    3    6    2    6    4]
 [   1    2    0    0    3    5    1    3    2    1    3    3    0]
 [  26   18    7   77   78   65   51   92   85  141  220  224  161]
 [ 258  264  333  347  420  262  296  392  314  333  310  201  344]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   2    0    0    1    0    0    0    1    0    0    0    0    0]
 [2884 1885 1833 1300 1866 1620 1901 1783 1303 1648 1579 1081 1758]
 [2521 1517 1428 1257 1934 1531 1777 1665 1373 1941 1473 1272 1224]
 [ 693  570  656  587  805  662 1064  498  662 1014  710  641  593]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]]
X_train [[  16    9   21   20   17   21   14   12   15   10   18   21]
 [   0    0    1    0    4    3    3    0    0    0    0    0]
 [ 599  498  682  556  630  498  562  590  393  554  448  462]
 [ 352  335  365  360  431  477  403  348  271  562  525  512]
 [   0    0    0    0    0    1    0    0    0    0    0    1]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    1    4    2    0    1    0    3    0    1    0    1]
 [  20   35   52   79   65   74   78   67   57   47   50   44]
 [   0    3    0    0    0    1    0    0    0    1    0    0]
 [   4    5    3   11    8    5    5    1    4    4    9    4]
 [ 263  247  239  179  223  277  281  288  184  202  206  120]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [  15   22   27   17   36   37   33   40   26   27   19   16]
 [  33   24   25   25   29   23   26   13   12   21   25   16]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   9    6   20    7   18   10   12   23   32   28   40    9]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [ 870  686  766  451  648  772 1006  816  679  693  566  821]
 [ 423  356  399  351  520  624  401  296  358  428  509  471]
 [  97  149  228  142  155  204  182  196  247  220  156  128]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    1    0    0]
 [   4    0    5    5    0    0    0    1    0    0    0    0]
 [   3    5    9    5    5    8   12    5    5    7    7    2]
 [   2    6   33   10   72   68   56   51   34   52   46   43]
 [  55  119  171   92  169  159  137  122  158  145  161  132]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    1    1    0    0    0]
 [  14   30   40   42   91   47   32   28   32   39   23   56]
 [  22   17   18   18   10   17   16   30   25   23   22   10]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [  26   32   28   31   30   37   28   24   26   26   48   28]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    1    1    1    1]
 [ 191  239  319  249  325  296  294  237  266  247  287  194]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [ 362  410  387  387  422  421  469  435  298  376  447  456]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [ 136  262  512  104  222  414  381  681  553  324  299  351]
 [   0    0    0    4    2    0    0    0    1    0    0    0]
 [   2    6    1    0    0    0    1    0    1    1    0    1]
 [ 127  134  327  328  382  364  277  348  432  518  530  244]
 [ 622  551  578  534  771  683  685  472  414  547  477  481]
 [1029  621  867  547  743  569  749  531  426  707  479  225]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    2   14    7    4    5    3    1    4    3    3    2]
 [ 168   84  131   92  109  107  124  100   69   75   74   57]
 [ 169  175  243  191  241  195  204  103  220  234  233  307]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [ 665  463  491  438  517  512  489  476  354  438  447  578]
 [   1    5    0    1    2    8    8   13    3    6    2    6]
 [   1    2    0    0    3    5    1    3    2    1    3    3]
 [  26   18    7   77   78   65   51   92   85  141  220  224]
 [ 258  264  333  347  420  262  296  392  314  333  310  201]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   2    0    0    1    0    0    0    1    0    0    0    0]
 [2884 1885 1833 1300 1866 1620 1901 1783 1303 1648 1579 1081]
 [2521 1517 1428 1257 1934 1531 1777 1665 1373 1941 1473 1272]
 [ 693  570  656  587  805  662 1064  498  662 1014  710  641]
 [   0    0    0    0    0    0    0    0    0    0    0    0]]
Y_train [[  15]
 [   0]
 [ 429]
 [ 368]
 [   0]
 [   0]
 [   0]
 [  28]
 [   0]
 [   5]
 [ 146]
 [   0]
 [   0]
 [  24]
 [  16]
 [   0]
 [  22]
 [   0]
 [ 942]
 [ 549]
 [  97]
 [   0]
 [   0]
 [   0]
 [   2]
 [  32]
 [ 111]
 [   0]
 [   0]
 [   0]
 [  21]
 [  30]
 [   0]
 [  55]
 [   0]
 [   0]
 [ 280]
 [   0]
 [ 374]
 [   0]
 [ 337]
 [   0]
 [   3]
 [ 472]
 [ 334]
 [ 592]
 [   0]
 [   0]
 [  59]
 [ 114]
 [   0]
 [   0]
 [ 360]
 [   4]
 [   0]
 [ 161]
 [ 344]
 [   0]
 [   0]
 [   0]
 [   0]
 [1758]
 [1224]
 [ 593]
 [   0]]

AttributeError: 'numpy.ndarray' object has no attribute 'append'